"""Markdown formatter for daily reports."""

from datetime import datetime
from typing import Dict, List, Optional
from collections import defaultdict
from src.models.analysis import AnalysisResult, CategoryType
from src.models.report import DailyReport
from src.models.deep_analysis import DeepAnalysis


class MarkdownFormatter:
    """Formats analysis results into markdown reports."""

    # Category emojis
    CATEGORY_EMOJIS = {
        "Breaking News": "🔥",
        "Research": "🔬",
        "Tools/Products": "🛠️",
        "Business": "💼",
        "Tutorial": "📚",
    }

    CATEGORY_NAMES_CN = {
        "Breaking News": "重大新聞",
        "Research": "學術研究",
        "Tools/Products": "工具與產品",
        "Business": "商業動態",
        "Tutorial": "技術教程",
    }

    CATEGORY_HASHTAGS = {
        "Breaking News": "#AI快訊 #AINews",
        "Research": "#AI研究 #AIResearch",
        "Tools/Products": "#AI工具 #AITools",
        "Business": "#AI商業 #AIBusiness",
        "Tutorial": "#AI教程 #AITutorial",
    }

    # Channel header template - sent once at the start
    CHANNEL_HEADER_TEMPLATE = """🤖 *AI快訊*
📅 {{ push_time }}
{{ divider }}
本期精選 *{{ total_articles }}* 則 AI 資訊
以下逐則播送 👇"""

    # Individual channel post template - one per article
    CHANNEL_POST_TEMPLATE = """{{ category_emoji }} *{{ category_name }}*

*{{ title }}* {{ stars }}
_📰 {{ source }}_

{{ summary }}
💡 _{{ insight }}_
{% if deep %}{% if deep_technologies %}
🔧 *關鍵技術*: {{ deep_technologies }}
{% endif %}{% if deep_insights %}
🎯 *核心洞察*:
{% for item in deep_insights %}  • {{ item }}
{% endfor %}{% endif %}{% if deep_impact %}
📊 *影響等級* {{ deep_impact_level }}/5
  → {{ deep_impact }}
{% endif %}{% if deep_actions %}
✅ {{ deep_actions }}
{% endif %}{% endif %}
🔗 [閱讀原文]({{ url }})

{{ hashtags }}"""

    # 改进的Telegram消息模板 - 更清晰易读
    TELEGRAM_TEMPLATE = """🤖 *AI快訊*
📅 {{ push_time }}
{{ divider }}
📊 *本期摘要* · 共 *{{ total_articles }}* 則

{% set ns = namespace(num=1) %}
{% for category, articles in articles_by_category.items() %}
{% if articles %}
{{ divider }}
*{{ category_emoji[category] }} {{ category_names[category] }}* ({{ articles|length }}則)
{{ divider }}

{% for analysis in articles %}
{% set deep = deep_analyses_map.get(analysis.article.url) %}
*{{ ns.num }}. {{ escape(analysis.title_cn) }}* {{ importance_stars(analysis.importance_score) }}
_來源: {{ escape(analysis.article.source) }}_

💭 {{ escape(analysis.summary) }}
💡 _{{ escape(analysis.insight) }}_
{% if deep %}

🔍 *深度分析*
{% if deep.technical_context.background %}
  📖 *技術背景*: {{ escape(deep.technical_context.background) }}
{% endif %}
{% if deep.technical_context.key_technologies %}
  🔧 *關鍵技術*: {{ deep.technical_context.key_technologies|join(', ') }}
{% endif %}
{% if deep.key_insights %}
  🎯 *核心洞察*:
{% for insight in deep.key_insights %}
    • {{ escape(insight) }}
{% endfor %}
{% endif %}
{% if deep.impact %}
  📊 *影響分析* ({{ deep.impact.impact_level }}/5):
    → 直接影響: {{ escape(deep.impact.immediate_impact) }}
    → 長期影響: {{ escape(deep.impact.long_term_impact) }}
{% if deep.impact.affected_sectors %}
    → 受影響領域: {{ deep.impact.affected_sectors|join(', ') }}
{% endif %}
{% endif %}
{% if deep.guidance and deep.guidance.action_items %}
  💼 *實踐建議*:
{% for action in deep.guidance.action_items %}
    ✅ {{ escape(action) }}
{% endfor %}
{% endif %}
{% if deep.controversies %}
  ⚠️ *爭議點*:
{% for controversy in deep.controversies %}
    • {{ escape(controversy) }}
{% endfor %}
{% endif %}
{% endif %}
🔗 [閱讀原文]({{ analysis.article.url }})

{% set ns.num = ns.num + 1 %}
{% endfor %}
{% endif %}
{% endfor %}
{{ divider }}
_🤖 Auto-generated by AI News Brief_
"""

    @staticmethod
    def escape_markdown(text: str) -> str:
        """Escape special characters for Telegram Markdown (V1) format.

        Args:
            text: Text to escape

        Returns:
            Escaped text safe for Telegram Markdown
        """
        if not text:
            return ""
        # Characters that need to be escaped in Telegram Markdown (V1)
        # We only really need to escape _, *, [ and ` for V1
        special_chars = ['_', '*', '`']
        for char in special_chars:
            text = text.replace(char, f'\\{char}')
        return text

    def __init__(self):
        """Initialize markdown formatter."""
        from jinja2 import Template
        self.telegram_template = Template(self.TELEGRAM_TEMPLATE)
        self.channel_header_template = Template(self.CHANNEL_HEADER_TEMPLATE)
        self.channel_post_template = Template(self.CHANNEL_POST_TEMPLATE)


    @staticmethod
    def _importance_stars(score: int) -> str:
        """Convert importance score to star rating.

        Args:
            score: Importance score (0-10)

        Returns:
            Star rating string (e.g., "⭐⭐⭐")
        """
        if score >= 9:
            star_count = 5
        elif score >= 7:
            star_count = 4
        elif score >= 5:
            star_count = 3
        elif score >= 3:
            star_count = 2
        else:
            star_count = 1
        return "⭐" * star_count

    @staticmethod
    def _importance_icon(score: int) -> str:
        """Convert importance score to color icon.

        Args:
            score: Importance score (0-10)

        Returns:
            Color icon indicating importance level
        """
        if score >= 8:
            return "🔴"  # High importance
        elif score >= 6:
            return "🟡"  # Medium importance
        else:
            return "🟢"  # Normal importance

    def format(
        self,
        date: datetime,
        analyzed_articles: List[AnalysisResult],
        deep_analyses: Optional[List[DeepAnalysis]] = None
    ) -> DailyReport:
        """Format analyzed articles into a daily report.

        Args:
            date: Report date
            analyzed_articles: List of analyzed articles
            deep_analyses: Optional list of deep analyses for high-value articles

        Returns:
            DailyReport object
        """
        # Group articles by category and sort by importance
        articles_by_category = self._group_by_category(analyzed_articles)

        # Create deep analyses map for quick lookup
        deep_analyses_map = {}
        if deep_analyses:
            deep_analyses_map = {deep.article_url: deep for deep in deep_analyses}

        # Calculate statistics
        total_articles = len(analyzed_articles)
        average_importance = (
            sum(a.importance_score for a in analyzed_articles) / total_articles
            if total_articles > 0
            else 0
        )

        # Generate markdown (Telegram format)
        push_time = datetime.now().strftime("%Y-%m-%d %H:%M")
        markdown_content = self.telegram_template.render(
            date=date.strftime("%Y-%m-%d"),
            push_time=push_time,
            total_articles=total_articles,
            average_importance=f"{average_importance:.1f}",
            articles_by_category=articles_by_category,
            deep_analyses_map=deep_analyses_map,
            category_emoji=self.CATEGORY_EMOJIS,
            category_names=self.CATEGORY_NAMES_CN,
            divider="─" * 30,
            importance_stars=self._importance_stars,
            importance_icon=self._importance_icon,
            escape=self.escape_markdown,
            generation_time=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        )

        # Generate individual channel posts
        individual_messages = self.format_channel_posts(
            push_time=push_time,
            total_articles=total_articles,
            articles_by_category=articles_by_category,
            deep_analyses_map=deep_analyses_map,
        )

        return DailyReport(
            date=date,
            articles_by_category=articles_by_category,
            markdown_content=markdown_content,
            individual_messages=individual_messages,
            total_articles=total_articles,
            average_importance=average_importance,
        )

    def format_channel_posts(
        self,
        push_time: str,
        total_articles: int,
        articles_by_category: Dict[CategoryType, List[AnalysisResult]],
        deep_analyses_map: Dict,
    ) -> List[str]:
        """Generate individual channel post messages (header + one per article).

        Args:
            push_time: Formatted push time string
            total_articles: Total number of articles
            articles_by_category: Articles grouped and sorted by category
            deep_analyses_map: Map of article URL to DeepAnalysis

        Returns:
            List of formatted messages: [header, article1, article2, ...]
        """
        messages = []

        # Header message
        header = self.channel_header_template.render(
            push_time=push_time,
            total_articles=total_articles,
            divider="─" * 30,
        )
        messages.append(header.strip())

        # One post per article
        for category, articles in articles_by_category.items():
            emoji = self.CATEGORY_EMOJIS.get(category, "📌")
            category_name = self.CATEGORY_NAMES_CN.get(category, category)
            hashtags = self.CATEGORY_HASHTAGS.get(category, "#AI")

            for analysis in articles:
                deep = deep_analyses_map.get(analysis.article.url)

                # Prepare deep analysis fields
                deep_technologies = ""
                deep_insights: List[str] = []
                deep_impact = ""
                deep_impact_level = 0
                deep_actions = ""

                if deep:
                    if deep.technical_context and deep.technical_context.key_technologies:
                        deep_technologies = self.escape_markdown(
                            ", ".join(deep.technical_context.key_technologies)
                        )
                    if deep.key_insights:
                        deep_insights = [
                            self.escape_markdown(i) for i in deep.key_insights[:3]
                        ]
                    if deep.impact:
                        deep_impact_level = deep.impact.impact_level
                        deep_impact = self.escape_markdown(
                            deep.impact.immediate_impact or ""
                        )
                    if deep.guidance and deep.guidance.action_items:
                        deep_actions = self.escape_markdown(
                            deep.guidance.action_items[0]
                        )

                post = self.channel_post_template.render(
                    category_emoji=emoji,
                    category_name=category_name,
                    title=self.escape_markdown(analysis.title_cn or analysis.article.title),
                    stars=self._importance_stars(analysis.importance_score),
                    source=self.escape_markdown(analysis.article.source),
                    summary=self.escape_markdown(analysis.summary),
                    insight=self.escape_markdown(analysis.insight),
                    url=analysis.article.url,
                    hashtags=hashtags,
                    deep=deep,
                    deep_technologies=deep_technologies,
                    deep_insights=deep_insights,
                    deep_impact=deep_impact,
                    deep_impact_level=deep_impact_level,
                    deep_actions=deep_actions,
                )
                messages.append(post.strip())

        return messages

    def _group_by_category(
        self, articles: List[AnalysisResult]
    ) -> Dict[CategoryType, List[AnalysisResult]]:
        """Group articles by category and sort by importance.

        Args:
            articles: List of analyzed articles

        Returns:
            Dict mapping category to sorted list of articles
        """
        grouped: Dict[CategoryType, List[AnalysisResult]] = defaultdict(list)

        for article in articles:
            grouped[article.category].append(article)

        # Sort each category by importance score (descending)
        for category in grouped:
            grouped[category].sort(key=lambda x: x.importance_score, reverse=True)

        # Return in desired order
        ordered_categories = ["Breaking News", "Research", "Tools/Products", "Business", "Tutorial"]
        return {cat: grouped[cat] for cat in ordered_categories if cat in grouped}

    def _format_relative_time(self, dt: datetime) -> str:
        """Format datetime as relative time string.

        Args:
            dt: Datetime to format

        Returns:
            Relative time string (e.g., "2小時前")
        """
        now = datetime.now()
        if dt.tzinfo is not None:
            dt = dt.replace(tzinfo=None)

        delta = now - dt
        days = delta.days
        hours = delta.seconds // 3600
        minutes = delta.seconds // 60

        if days > 0:
            return f"{days}天前"
        if hours > 0:
            return f"{hours}小時前"
        if minutes > 0:
            return f"{minutes}分鐘前"
        return "剛剛"

    def format_telegram_message(self, data: DailyReport) -> str:
        """Format complete Telegram message.

        Args:
            data: Daily report data

        Returns:
            Formatted Telegram message
        """
        return data.markdown_content

    def format_markdown_report(self, data: DailyReport) -> str:
        """Format complete Markdown report.

        Args:
            data: Daily report data

        Returns:
            Formatted Markdown report
        """
        return data.markdown_content
