"""Markdown formatter for daily reports."""

from datetime import datetime
from typing import Dict, List, Optional
from collections import defaultdict
from jinja2 import Template
from src.models.analysis import AnalysisResult, CategoryType
from src.models.report import DailyReport
from src.models.deep_analysis import DeepAnalysis


class MarkdownFormatter:
    """Formats analysis results into markdown reports."""

    # Category emojis
    CATEGORY_EMOJIS = {
        "Breaking News": "🔥",
        "Research": "🔬",
        "Tools/Products": "🛠️",
        "Business": "💼",
        "Tutorial": "📚",
    }

    CATEGORY_NAMES_CN = {
        "Breaking News": "重大新聞",
        "Research": "學術研究",
        "Tools/Products": "工具與產品",
        "Business": "商業動態",
        "Tutorial": "技術教程",
    }

    TEMPLATE = """🤖 *AI快訊*
⏰ {{ push_time }}
━━━━━━━━━━━━
📊 *本期摘要* · 共 {{ total_articles }} 則
{% set ns = namespace(num=1) -%}
{% for category, articles in articles_by_category.items() -%}
{% if articles -%}

{{ category_emoji[category] }} *{{ category_names[category] }}*
{% for analysis in articles -%}
{% set deep = deep_analyses_map.get(analysis.article.url) -%}
*{{ ns.num }}.* *{{ escape(analysis.title_cn) }}* {{ importance_stars(analysis.importance_score) }}
┃ {{ escape(analysis.summary) }}
┃ 💡 _{{ escape(analysis.insight) }}_
{% if deep -%}
┃
┃ 🔍 *深度分析*
┃
┃ 📖 *技術背景*
┃ {{ escape(deep.technical_context.background) }}
{% if deep.technical_context.key_technologies -%}
┃ 關鍵技術: {{ deep.technical_context.key_technologies|join(', ') }}
{% endif -%}
┃
┃ 🎯 *核心洞察*
{% for insight in deep.key_insights -%}
┃ • {{ escape(insight) }}
{% endfor -%}
┃
┃ 📊 *影響分析* (影響等級: {{ deep.impact.impact_level }}/5)
┃ 直接影響: {{ escape(deep.impact.immediate_impact) }}
┃ 長期影響: {{ escape(deep.impact.long_term_impact) }}
{% if deep.impact.affected_sectors -%}
┃ 受影響領域: {{ deep.impact.affected_sectors|join(', ') }}
{% endif -%}
{% if deep.guidance and deep.guidance.action_items -%}
┃
┃ 💼 *實踐建議*
{% for action in deep.guidance.action_items -%}
┃ ✅ {{ escape(action) }}
{% endfor -%}
{% endif -%}
{% if deep.controversies -%}
┃
┃ ⚠️ *爭議點*
{% for controversy in deep.controversies -%}
┃ • {{ escape(controversy) }}
{% endfor -%}
{% endif -%}
{% endif -%}
└ 🔗 [{{ escape(analysis.article.source) }}]({{ analysis.article.url }})
{% if not loop.last %}

{% endif -%}
{% set ns.num = ns.num + 1 -%}
{% endfor -%}
{% endif -%}
{% endfor -%}
━━━━━━━━━━━━
📡 _Auto-generated by AI News Brief_
"""

    def __init__(self):
        """Initialize markdown formatter."""
        self.template = Template(self.TEMPLATE)

    @staticmethod
    def _escape_markdown(text: str) -> str:
        """Escape markdown special characters.

        Args:
            text: Text to escape

        Returns:
            Escaped text
        """
        if not text:
            return ""
        # Escape characters that have special meaning in Markdown
        chars_to_escape = ["_", "*", "`", "["]
        for char in chars_to_escape:
            text = text.replace(char, f"\\{char}")
        return text

    @staticmethod
    def _importance_stars(score: int) -> str:
        """Convert importance score to star rating.

        Args:
            score: Importance score (0-10)

        Returns:
            Star rating string (e.g., "⭐⭐⭐")
        """
        # Score thresholds: 9+ = 5 stars, 7+ = 4 stars, 5+ = 3 stars, 3+ = 2 stars, else 1 star
        star_count = 5 if score >= 9 else 4 if score >= 7 else 3 if score >= 5 else 2 if score >= 3 else 1
        return "⭐" * star_count

    def format(
        self,
        date: datetime,
        analyzed_articles: List[AnalysisResult],
        deep_analyses: Optional[List[DeepAnalysis]] = None
    ) -> DailyReport:
        """Format analyzed articles into a daily report.

        Args:
            date: Report date
            analyzed_articles: List of analyzed articles
            deep_analyses: Optional list of deep analyses for high-value articles

        Returns:
            DailyReport object
        """
        # Group articles by category and sort by importance
        articles_by_category = self._group_by_category(analyzed_articles)

        # Create deep analyses map for quick lookup
        deep_analyses_map = {}
        if deep_analyses:
            deep_analyses_map = {deep.article_url: deep for deep in deep_analyses}

        # Calculate statistics
        total_articles = len(analyzed_articles)
        average_importance = (
            sum(a.importance_score for a in analyzed_articles) / total_articles
            if total_articles > 0
            else 0
        )

        # Generate markdown
        push_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        markdown_content = self.template.render(
            date=date.strftime("%Y-%m-%d"),
            push_time=push_time,
            total_articles=total_articles,
            average_importance=f"{average_importance:.1f}",
            articles_by_category=articles_by_category,
            deep_analyses_map=deep_analyses_map,
            category_emoji=self.CATEGORY_EMOJIS,
            category_names=self.CATEGORY_NAMES_CN,
            format_time=self._format_relative_time,
            importance_stars=self._importance_stars,
            escape=self._escape_markdown,
            generation_time=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        )

        return DailyReport(
            date=date,
            articles_by_category=articles_by_category,
            markdown_content=markdown_content,
            total_articles=total_articles,
            average_importance=average_importance,
        )

    def _group_by_category(
        self, articles: List[AnalysisResult]
    ) -> Dict[CategoryType, List[AnalysisResult]]:
        """Group articles by category and sort by importance.

        Args:
            articles: List of analyzed articles

        Returns:
            Dict mapping category to sorted list of articles
        """
        grouped: Dict[CategoryType, List[AnalysisResult]] = defaultdict(list)

        for article in articles:
            grouped[article.category].append(article)

        # Sort each category by importance score (descending)
        for category in grouped:
            grouped[category].sort(key=lambda x: x.importance_score, reverse=True)

        # Return in desired order
        ordered_categories = ["Breaking News", "Research", "Tools/Products", "Business", "Tutorial"]
        return {cat: grouped[cat] for cat in ordered_categories if cat in grouped}

    def _format_relative_time(self, dt: datetime) -> str:
        """Format datetime as relative time string.

        Args:
            dt: Datetime to format

        Returns:
            Relative time string (e.g., "2小時前")
        """
        now = datetime.now()
        if dt.tzinfo is not None:
            dt = dt.replace(tzinfo=None)

        delta = now - dt
        days = delta.days
        hours = delta.seconds // 3600
        minutes = delta.seconds // 60

        if days > 0:
            return f"{days}天前"
        if hours > 0:
            return f"{hours}小時前"
        if minutes > 0:
            return f"{minutes}分鐘前"
        return "剛剛"
